---
title: "A3: Incarceration"
output: html_document
---

### Introduction

In the United States, the associated issues with incarceration has gained significant attention because of how it has impacted individuals, communities, and society as a whole. An important aspect of this problem that I have focused on is the disproportionately high number of individuals incarcerated, particularly among people of color, and the historical injustices that have perpetuated this disparity. 

### Summary Information

After analyzing this dataset, the following statistics provide an initial overview of the incarceration data and offers a preview into the key variables that I have assessed on the disparities in incarceration rates based on race and gender. The variables of focus that I have chosen to explore are:

*Total Jail Population Rate*
This variable encapsulates the overall incarceration rate in jails per 100,000 people, offering a basic understanding of the extent of incarceration in different regions over time.

*White Jail Population Rate*
The incarceration rate of White individuals in jails per 100,000 people. This variable serves as a baseline for comparison, allowing us to contrast the experiences of different racial groups

*Black Jail Population Rate*
The incarceration rate of Black individuals in jails per 100,000 people. This variable highlights the a critical racial disparity within the criminal justice system.

*Latinx Jail Population Rate*
The incarceration rate of Latinx individuals in jails per 100,000 people. This variable helps to provide another example of the inequalities faced by the Latinx community in the context of incarceration.

*Female Jail Population Rate*
The incarceration rate of females in jails per 100,000 people. Gender dynamics play an important role in understanding the distinct challenges that are faced by women within the criminal justice system.

*Male Jail Population Rate*
The incarceration rate of males in jails per 100,000 people. By contrasting the incarceration experiences of men and women, we can explore potential disparities and gender-specific factors contributing to incarceration rates.

The relevant values of interest that I have focused on are:

*Average Total Jail Population Rate* 
By calculating the average incarceration rate across all counties and states for the current year, we gain insight into the overall magnitude of the issue.

*County with Highest Black Jail Population Rate* 
By identifying the county with the highest Black jail population rate, we can see the localized instance of the racial disparities that occur.

*County with Lowest White Jail Population Rate*
By highlighting the county with the lowest White jail population rate, we are given an idea of potential variations in incarceration experiences.

*Change in Latinx Jail Population Rate Over Last 10 Years*
By figuring out the change in the Latinx jail population rate over the last decade, we discern trends that could lead to evolving dynamics within the criminal justice system.

*Largest Disparity Between Male and Female Jail Population Rates*
By calculating the county where the difference between male and female jail population rates is the most substantial, it is possible to figure out gender-specific factors impacting incarceration.


### The Dataset

prison_data <- read.csv("https://raw.githubusercontent.com/melaniewalsh/Neat-Datasets/main/us-prison-jail-rates-1990.csv")
summary(prison_data)

* Who collected the data?

This data was collected by the Vera Institute of Justice, a nonprofit organization that aims to address issues within the criminal justice system. They're known for well-known for its research and data-driven approach to understanding and reforming the criminal justice system.

* How was the data collected or generated?  

The data was collected through a combination of Bureau of Justice Statistics (BJS) data collections, including the Census of Jails (COJ) and the Annual Survey of Jails (ASJ). Every 5 - 8 years the COJ covers all jails, while every non-census years the ASJ covers around one third of jails. This data is then collected from various jails around the US and added to the dataset.

* Why was the data collected? 

The data was collected to provide  insights into incarceration trends and disparities in the United States. The goal was to create a dataset that allows researchers, policymakers, and the public to understand the dynamics of incarceration, particularly within jails. The data helps share the factors contributing to high rates of incarceration and disparities based on race, gender, location, and other factors. 

* How many observations (rows) are in your data?  

There are a total of 91,031 observations in this dataset.

* How many features (columns) are in the data?  

There are a total 23 features in this datasset.

* What, if any, ethical questions or questions of power do you need to consider when working with this data?  

When working with incarceration data, ethical questions about privacy, consent, and potential biases can rise up. It's important to ensure that the data analysis and interpretation does not perpetuate stereotypes or stigmatize certain communities. Additionally, the power dynamics within the criminal justice system must also be considered, as data can reflect systemic injustices. 

* What are possible limitations or problems with this data?

Immediately, we can see that the dataset relies on reported data from jails and prisons. This might not always be accurately reported and does not reveal the entire scope of incarceration due to reporting inconsistencies The dataset might not capture nuances within demographic groups, and there could be underreporting of certain groups due to systemic factors. 


### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

